### ISSUE TITLE
Club | Profile of an Artist

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/wsvvrijheid#51] opened 2022-04-10 21:21 UTC
### Describe the feature you'd like to request

Profil detail who is not login. Each art has artist. we should see each artist detail

### Describe the solution you'd like

show user detail
     
Users arts

**Comment by 7alip** [comment] 2022-05-22 19:27
Duplicate of #95

**Closed by 7alip** 2022-05-22 19:27 UTC
Labels: enhancement
